services:
  postgres:
    image: postgis/postgis:latest
    build:
      context: postgres/
      dockerfile: Dockerfile
    container_name: geoapp_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: geoapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    container_name: geoapp_backend
    restart: always
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: geoapp
    depends_on:
      - postgres
    ports:
      - "8000:8000"

volumes:
  postgres_data:
